title: Rens Ramos
email: rensramos17@gmail.com
description: >
  A developer who is passionate in developing and designing awesome website.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


sass:
    style: compressed
# Build settings
markdown: kramdown


project-filter:
  - name: All
    filter: "all"
    
  - name: Web Dev
    filter: ".web-dev"

  - name: Web Design
    filter: ".web-design"

  - name: Graphic
    filter: ".graphic"

  - name: Typography
    filter: ".typography"

