title: Rens Ramos
email: rensramos17@gmail.com
description: >
  A developer who is passionate in developing and designing awesome website.

baseurl: "/rensramos/"
url: ""

sass:
    style: compressed
# Build settings
markdown: kramdown

plugins:
  - jekyll-gzip

gzip:
  replace_files: true
  extensions:
    - '.html'
    - '.css'
    - '.js'

project-filter:
  - name: All
    filter: "all"
    
  - name: Web Dev
    filter: ".web-dev"

  - name: Web Design
    filter: ".web-design"

  - name: Graphic
    filter: ".graphic"

  - name: Typography
    filter: ".typography"

