title: Rens Ramos
email: rensramos17@gmail.com
description: >
  A young developer who is passionate in developing and designing awesome website.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


sass:
    style: compressed
# Build settings
markdown: kramdown

collections:
  work:
    output: true
    permalink: /product/:path/

project-filter:
  - id: 1
    name: Web Dev
    filter: ".web-dev"

  - id: 2
    name: Web Design
    filter: ".web-design"

  - id: 3
    name: Graphic
    filter: ".graphic"

  - id: 4
    name: Typography
    filter: ".typography"

