---
- title: Project Agape
  rank: 17
  role: Web Dev
  type: web-dev
  image: project-agape.png
  link: project-agape.github.io/
  bg-color: e84874
- title: Ghost Gaming
  rank: 17
  role: Graphic
  type: graphic
  image: ghost-logo.png
  link: www.behance.net/gallery/68150123/Ghost-Gaming-logo
  bg-color: 13414e
- title: Fleur Oils
  rank: 16
  role: Web Dev
  type: web-dev
  image: fleuroils.jpg
  link:
  bg-color: 478dc9
- title: Father's Day
  rank: 1
  role: Typography
  type: typography
  image: fathersday.jpg
  link: behance.net/gallery/27322577/Fathers-day-typography
  bg-color: 13414e
- title: Nature's Prophet
  rank: 2
  role: Graphic
  type: graphic
  image: naturesprophet.jpg
  link: behance.net/gallery/23766467/Nature-Prophet
  bg-color: 00bbb0
- title: PHWash Resources
  rank: 3
  role: Web Dev
  type: web-dev
  image: phwash.jpg
  link: www.phwashresources.com
  bg-color: de4825
- title: Foxconn Builders
  rank: 4
  role: WEB DEV
  type: web-dev
  image: foxconn.jpg
  link: www.foxconnbuilders.com
  bg-color: 478dc9
- title: Fashion21 Cosmetics
  rank: 5
  role: Web Dev
  type: web-dev
  image: fashion21.jpg
  link: www.fashion21cosmetics.com
  bg-color: 13414e
- title: FS Cosmetics
  rank: 6
  role: Web Dev
  type: web-dev
  image: fscosmetics.jpg
  link: www.fscosmetics.com
  bg-color: e84874
- title: Mystery Manila
  rank: 7
  role: Web Dev
  type: web-dev
  image: mysterymanila.jpg
  link: www.mysterymanila.com
  bg-color: 13414e
- title: Josan & Bryan
  rank: 8
  role: Web Dev / Web Design
  type: web-dev web-design
  image: wedding-website.jpg
  link: josanandbryanwedding.github.io
  bg-color: 00bbb0
- title: Threelogy Video
  rank: 9
  role: Web Dev
  type: web-dev
  image: threelogy.jpg
  link: www.threelogyvideo.com
  bg-color: ba2e31
- title: Hugbig Photography Website
  rank: 10
  role: Web Dev / Web Design
  type: web-dev web-design
  image: hugbig.jpg
  link: hugbigphotography.github.io
  bg-color: de4825
- title: SNAP Website
  rank: 11
  role: Web Dev
  type: web-dev
  image: snap.jpg
  link: www.snaboitiz.com
  bg-color: 273744
- title: SNAP RES Website
  rank: 12
  role: Web Dev
  type: web-dev
  image: snap-res.jpg
  link: www.snap-res.com
  bg-color: de4825
- title: AOTCA 2017
  rank: 13
  role: Web Dev / Web Design / Forms
  type: web-dev web-design
  image: aotca2017.jpg
  link:
  bg-color: e84874
- title: Pocket Rocket Agency
  rank: 14
  role: Web Dev / Forms
  type: web-dev
  image: pocketrocket.jpg
  link: www.pocketrocketinc.com
  bg-color: 00bbb0
- title: MyPartyPix Photobooth
  rank: 15
  role: Web Dev / Web Design
  type: web-dev web-design
  image: mypartypix.jpg
  link:
  bg-color: 13414e
